

export const ADD_BLOG_REQUEST = 'ADD_BLOG_REQUEST';
export const ADD_BLOG_SUCCESS = 'ADD_BLOG_SUCCESS';
export const ADD_BLOG_ERROR = 'ADD_BLOG_ERROR';

export const GET_ALL_BLOG_REQUEST = 'GET_ALL_BLOG_REQUEST';
export const GET_ALL_BLOG_SUCCESS = 'GET_ALL_BLOG_SUCCESS';
export const GET_ALL_BLOG_ERROR = 'GET_ALL_BLOG_ERROR';

export const GET_USER_BLOG_REQUEST = 'GET_USER_BLOG_REQUEST';
export const GET_USER_BLOG_SUCCESS = 'GET_USER_BLOG_SUCCESS';
export const GET_USER_BLOG_ERROR = 'GET_USER_BLOG_ERROR';


export const GET_USER_REQUEST = 'GET_USER_REQUEST';
export const GET_USER_SUCCESS = 'GET_USER_SUCCESS';
export const GET_USER_ERROR = 'GET_USER_ERROR';

export const UPADATE_USER_INFO_REQUEST = 'UPADATE_USER_INFO_REQUEST';
export const UPADATE_USER_INFO_SUCCESS = 'UPADATE_USER_INFO_SUCCESS';
export const UPADATE_USER_INFO_ERROR = 'UPADATE_USER_INFO_ERROR';

export const UPDATE_BLOG_REQUEST = 'UPDATE_BLOG_REQUEST';
export const UPDATE_BLOG_SUCCESS = 'UPDATE_BLOG_SUCCESS';
export const UPDATE_BLOG_ERROR = 'UPDATE_BLOG_ERROR';

export const DELETE_BLOG_REQUEST = 'DELETE_BLOG_REQUEST';
export const DELETE_BLOG_SUCCESS = 'DELETE_BLOG_SUCCESS';
export const DELETE_BLOG_ERROR = 'DELETE_BLOG_ERROR';
